version: '2.1'
x-app: &app
  image: ridhoq/soundslike
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    FLASK_CONFIG: development
    DEV_DATABASE_URL: postgres://postgres:soundslike_password@db:5432/postgres
services:
  app:
    <<: *app
    command: bash -c "python manage.py runserver --host 0.0.0.0 & npm run dev"
    ports:
      - "8888:5000"
    depends_on:
      migrate_db:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./client/:/soundslike/client
      - ./server:/soundslike/server
      - /soundslike/server/static
  migrate_db:
    <<: *app
    command: python manage.py db upgrade
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: soundslike_password
  